DROP TABLE IF EXISTS transaction CASCADE;
DROP TABLE IF EXISTS regola_classificazione CASCADE;
DROP TABLE IF EXISTS center CASCADE;

-- V2__crea_tabelle_transaction_centri.sql

-- Tabella CENTRO
CREATE TABLE center (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    tipo VARCHAR(255) NOT NULL CHECK (tipo IN ('COSTO','PROFITTO'))
);

-- Tabella MOVIMENTO
CREATE TABLE transaction (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transactionId VARCHAR(255),
    bookingDate TIMESTAMP WITH TIME ZONE,
    valueDate TIMESTAMP WITH TIME ZONE,
    currency SMALLINT CHECK (currency BETWEEN 0 AND 27),
    amount NUMERIC(38,2),
    remittanceInformation VARCHAR(255),
    creditorName VARCHAR(255),
    debtorName VARCHAR(255),
    bankTransactionCode VARCHAR(255),
    additionalInformation VARCHAR(255),
    proprietaryBankTransactionCode VARCHAR(255),
    accountId VARCHAR(255),
    center_id BIGINT NOT NULL,
    CONSTRAINT fk_transaction_center FOREIGN KEY (center_id) REFERENCES center(id)
);

-- Tabella REGOLA_CLASSIFICAZIONE
CREATE TABLE regola_classificazione (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    keyword VARCHAR(255) NOT NULL,
    center_id BIGINT NOT NULL,
    CONSTRAINT fk_regola_center FOREIGN KEY (center_id) REFERENCES center(id)
);
